sideimage:~/Desktop/Storage/C++/ascinfo/ascinfo.sideimage
base_color:#57C7FF
secondary_color:#FF6AC1

[SYSTEM]
OS,pretty_name,\uf31a
Kernel,kernel,\uf305
Arch.,architecture,\ue225
IP,ip,\ueb1c

[DESKTOP]
DE,de,\uf4a9
Packages,pkmg,\uf487
Shell,shell,\uebca
Terminal,terminal,\uf489
Theme,desktop_theme,\uf4a9

[HARDWARE]
CPU,cpu,\ue266
C. Temp,cpu_temp,\ueaf2
GPU,gpu,\ue266
G. Temp,gpu_temp,\ueaf2
RAM,used_mem,󰄩

[USAGE]
Up,uptime,\ue641
Sys. Age,sys_age,\uea98

